export enum MuscleGroup {
  CHEST = "Chest",
  TRICEPS = "Triceps",
  SHOULDERS = "Shoulders",
  BACK = "Back",
  BICEPS = "Biceps",
  QUADS = "Quads",
  GLUTES = "Glutes",
  HAMSTRINGS = "Hamstrings",
  ADDUCTORS = "Adductors",
  CALVES = "Calves",
}

export const exercises = {
  "Flat Bench Press (Barbell)": [
    MuscleGroup.CHEST,
    MuscleGroup.TRICEPS,
    MuscleGroup.SHOULDERS,
  ],
  "Incline Bench Press (Barbell)": [
    MuscleGroup.CHEST,
    MuscleGroup.TRICEPS,
    MuscleGroup.SHOULDERS,
  ],
  "Flat Bench Press (Dumbbell)": [
    MuscleGroup.CHEST,
    MuscleGroup.TRICEPS,
    MuscleGroup.SHOULDERS,
  ],
  "Incline Bench Press (Dumbbell)": [
    MuscleGroup.CHEST,
    MuscleGroup.TRICEPS,
    MuscleGroup.SHOULDERS,
  ],
  "Flat Chest Press (Machine)": [
    MuscleGroup.CHEST,
    MuscleGroup.TRICEPS,
    MuscleGroup.SHOULDERS,
  ],
  "Incline Chest Press (Machine)": [
    MuscleGroup.CHEST,
    MuscleGroup.TRICEPS,
    MuscleGroup.SHOULDERS,
  ],
  "Flat Bench Press (Smith Machine)": [
    MuscleGroup.CHEST,
    MuscleGroup.TRICEPS,
    MuscleGroup.SHOULDERS,
  ],
  "Incline Bench Press (Smith Machine)": [
    MuscleGroup.CHEST,
    MuscleGroup.TRICEPS,
    MuscleGroup.SHOULDERS,
  ],
  "Push-ups": [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
  Dips: [MuscleGroup.CHEST, MuscleGroup.TRICEPS, MuscleGroup.SHOULDERS],
  "Chest Fly (Machine)": [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
  "Chest Fly (Cable)": [MuscleGroup.CHEST, MuscleGroup.SHOULDERS],
  "Shoulder Press (Barbell)": [MuscleGroup.SHOULDERS],
  "Shoulder Press (Dumbbell)": [MuscleGroup.SHOULDERS],
  "Shoulder Press (Machine)": [MuscleGroup.SHOULDERS],
  "Shoulder Press (Smith Machine)": [MuscleGroup.SHOULDERS],
  "Lateral Raise (Dumbbell)": [MuscleGroup.SHOULDERS],
  "Lateral Raise (Machine)": [MuscleGroup.SHOULDERS],
  "Lateral Raise (Cable)": [MuscleGroup.SHOULDERS],
  "Reverse Fly (Dumbbell)": [MuscleGroup.SHOULDERS],
  "Reverse Fly (Machine)": [MuscleGroup.SHOULDERS],
  "Reverse Fly (Cable)": [MuscleGroup.SHOULDERS],
  "Triceps Pushdown (Machine)": [MuscleGroup.TRICEPS],
  "Triceps Pushdown (Cable)": [MuscleGroup.TRICEPS],
  "Triceps Overhead Extension (Dumbbell)": [MuscleGroup.TRICEPS],
  "Triceps Overhead Extension (Machine)": [MuscleGroup.TRICEPS],
  "Triceps Overhead Extension (Cable)": [MuscleGroup.TRICEPS],
  "Skullcrushers (Barbell)": [MuscleGroup.TRICEPS],
  "Lat Pulldown (Machine)": [MuscleGroup.BACK, MuscleGroup.BICEPS],
  "Lat Pulldown (Cable)": [MuscleGroup.BACK, MuscleGroup.BICEPS],
  "Pull-ups": [MuscleGroup.BACK, MuscleGroup.BICEPS],
  "SA High Row (Cable)": [MuscleGroup.BACK, MuscleGroup.BICEPS],
  "T-Bar Row (Machine)": [MuscleGroup.BACK, MuscleGroup.BICEPS],
  "Seated Row (Machine)": [MuscleGroup.BACK, MuscleGroup.BICEPS],
  "Seated Row (Cable)": [MuscleGroup.BACK, MuscleGroup.BICEPS],
  "Bent Over Row (Barbell)": [MuscleGroup.BACK, MuscleGroup.BICEPS],
  "Bent Over Row (Dumbbell)": [MuscleGroup.BACK, MuscleGroup.BICEPS],
  "Back Extension": [MuscleGroup.BACK],
  "Preacher Curl (Machine)": [MuscleGroup.BICEPS],
  "Preacher Curl (Barbell)": [MuscleGroup.BICEPS],
  "Preacher Curl (Dumbbell)": [MuscleGroup.BICEPS],
  "Bicep Curl (Barbell)": [MuscleGroup.BICEPS],
  "Bicep Curl (Dumbbell)": [MuscleGroup.BICEPS],
  "Bicep Curl (Cable)": [MuscleGroup.BICEPS],
  "Incline Bicep Curl (Dumbbell)": [MuscleGroup.BICEPS],
  "Front Squat (Barbell)": [MuscleGroup.QUADS],
  "Back Squat (Barbell)": [MuscleGroup.QUADS],
  "Back Squat (Smith Machine)": [MuscleGroup.QUADS],
  "Hack Squat (Machine)": [MuscleGroup.QUADS],
  "Pendulum Squat (Machine)": [MuscleGroup.QUADS],
  "Leg Extension (Machine)": [MuscleGroup.QUADS],
  "Sissy Squat": [MuscleGroup.QUADS],
  "Leg Press (Machine)": [MuscleGroup.QUADS, MuscleGroup.GLUTES],
  "Bulgarian Split Squat (Dumbbell)": [MuscleGroup.QUADS, MuscleGroup.GLUTES],
  "Bulgarian Split Squat (Smith Machine)": [
    MuscleGroup.QUADS,
    MuscleGroup.GLUTES,
  ],
  "Seated Leg Curl (Machine)": [MuscleGroup.HAMSTRINGS],
  "Seated Leg Curl (Cable)": [MuscleGroup.HAMSTRINGS],
  "Lying Leg Curl (Machine)": [MuscleGroup.HAMSTRINGS],
  "Stiff-Legged Deadlift (Machine)": [
    MuscleGroup.HAMSTRINGS,
    MuscleGroup.GLUTES,
  ],
  "Stiff-Legged Deadlift (Barbell)": [
    MuscleGroup.HAMSTRINGS,
    MuscleGroup.GLUTES,
  ],
  "Stiff-Legged Deadlift (Dumbbell)": [
    MuscleGroup.HAMSTRINGS,
    MuscleGroup.GLUTES,
  ],
  "Romanian Deadlift (Machine)": [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
  "Romanian Deadlift (Barbell)": [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
  "Romanian Deadlift (Dumbbell)": [MuscleGroup.HAMSTRINGS, MuscleGroup.GLUTES],
  "Nordic Hamstring Curl": [MuscleGroup.HAMSTRINGS],
  "Hip Thrust (Machine)": [MuscleGroup.GLUTES],
  "Hip Thrust (Smith Machine)": [MuscleGroup.GLUTES],
  "Hip Thrust (Barbell)": [MuscleGroup.GLUTES],
  "Glute Kickback (Machine)": [MuscleGroup.GLUTES],
  "Glute Kickback (Cable)": [MuscleGroup.GLUTES],
  "Abductors (Machine)": [MuscleGroup.GLUTES],
  "Adductors (Machine)": [MuscleGroup.ADDUCTORS],
  "Standing Calf Raise (Machine)": [MuscleGroup.CALVES],
  "Seated Calf Raise (Machine)": [MuscleGroup.CALVES],
};
